// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH5qloromD3ZCIhPXJjR4_aHNx8DNXnlI',
    appId: '1:749747768227:web:e259fa8b49a087def0e816',
    messagingSenderId: '749747768227',
    projectId: 'proof-of-concept-3d68c',
    authDomain: 'proof-of-concept-3d68c.firebaseapp.com',
    storageBucket: 'proof-of-concept-3d68c.appspot.com',
    measurementId: 'G-67C4GNZ2GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9JxzGaCiRtBloDJGkgQYyVGuLUAfVzg',
    appId: '1:749747768227:android:339e8ac439276989f0e816',
    messagingSenderId: '749747768227',
    projectId: 'proof-of-concept-3d68c',
    storageBucket: 'proof-of-concept-3d68c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsGU1_fmq-qJJITuvnQL6FSk4ilcG4us',
    appId: '1:749747768227:ios:10a0edc1c8c9e102f0e816',
    messagingSenderId: '749747768227',
    projectId: 'proof-of-concept-3d68c',
    storageBucket: 'proof-of-concept-3d68c.appspot.com',
    iosClientId: '749747768227-hcjjkcrb6eft2b08e95l0k1bsa9bku7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.proofOfConcept',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADsGU1_fmq-qJJITuvnQL6FSk4ilcG4us',
    appId: '1:749747768227:ios:10a0edc1c8c9e102f0e816',
    messagingSenderId: '749747768227',
    projectId: 'proof-of-concept-3d68c',
    storageBucket: 'proof-of-concept-3d68c.appspot.com',
    iosClientId: '749747768227-hcjjkcrb6eft2b08e95l0k1bsa9bku7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.proofOfConcept',
  );
}
